#- platform: command_line
#  name: Travis Status
#  command: /usr/bin/curl -s -X GET https://api.travis-ci.org/repos/cyberkov/home-assistant-config/cc.xml\?branch\=master | grep lastBuildStatus | cut -d'"' -f2
#  scan_interval: 60
#
#- platform: command_line
#  name: Travis Build Label
#  command: /usr/bin/curl -s -X GET https://api.travis-ci.org/repos/cyberkov/home-assistant-config/cc.xml\?branch\=master | grep lastBuildLabel | cut -d'"' -f2
#  scan_interval: 60
