- platform: darksky
  api_key: !secret HA_FORECAST_API
  language: de
  monitored_conditions:
    - summary
    - icon
    - precip_intensity
    - precip_probability
    - precip_type
    - hourly_summary
    - wind_speed
    - daily_summary
    - temperature
    - humidity
    - pressure
    - wind_bearing
    - apparent_temperature
