- platform: sonarr
  api_key: !secret HA_SONARR_APIKEY
  host: 192.168.1.4
  port: 8989
- platform: radarr
  api_key: !secret HA_RADARR_APIKEY
  host: 192.168.1.4
  port: 7878
  monitored_conditions:
    - upcoming
    - status
