---
alarm_control_panel:
  - platform: manual_mqtt
    name: House
    state_topic: home/alarm
    command_topic: home/alarm/set
    code: !secret HA_ALARM_CODE
    pending_time: 60
    trigger_time: 120
    delay_time: 30
    disarmed:
      trigger_time: 0
    armed_home:
      pending_time: 0
      delay_time: 0
    triggered:
      pending_time: 0
#automation:
