#- platform: wake_on_lan
#  mac_address: "00-11-32-0a-56-bd"
#  name: "NAS"
#  host: "192.168.1.5"
#- platform: wake_on_lan
#  mac_address: "00-1a-22-04-99-4b"
#  name: "CCU"
#  host: "192.168.1.6"
- platform: wake_on_lan
  mac: "94:c6:91:5f:da:d9"
  name: "pangea"
  host: "192.168.1.9"
  turn_off:
    service: shell_command.turn_off_pangea
