---
- alias: "Alarm tripped - bwalarm"
  initial_state: false
  trigger:
    - platform: state
      entity_id:
        - alarm_control_panel.house
      to: "triggered"
  action:
    - service: switch.turn_on
      entity_id: switch.meq0727791_2
    - service: switch.turn_on
      entity_id: switch.meq0727791_1
    - service: notify.hannes
      data_template:
        message: >
          ALARM - {{ trigger.to_state.attributes.changed_by }} triggered it.
    - service: notify.slack
      data_template:
        message: >
          ALARM - {{ trigger.to_state.attributes.changed_by }} triggered it.

- alias: "Alarm Warning"
  initial_state: false
  trigger:
    - platform: state
      entity_id: switch.warning
      from: "off"
      to: "on"
  action:
    - service: notify.slack
      data_template:
        message: >
          ALARM - Warnzeit aktiv. Alarmanlage ist {{ states("alarm_control_panel.house") }}.
