---
- alias: "Alarm Trigger - home"
  initial_state: true
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.leq1085620_state
        - binary_sensor.leq1177637_state
        - binary_sensor.meq0186561_state
        - binary_sensor.meq0186623_state
        - binary_sensor.meq0186642_state
      from: "off"
      to: "on"
      for:
        seconds: 20
  condition:
    - condition: state
      entity_id: alarm_control_panel.house
      state: "armed_home"
  action:
    - service: alarm_control_panel.alarm_trigger
      data:
        entity_id: alarm_control_panel.house
    - service: notify.slack
      data_template:
        message: >
          ALARM - {{ trigger.to_state.attributes.friendly_name }} triggered it.
