- alias: "Automation_Test"
  initial_state: True
  trigger:
    - platform: state
      entity_id: binary_sensor.meq0537387_motion
      to: "on"
  condition:
    - condition: state
      entity_id: switch.lavalampe
      state: "off"
  action:
    - service: homeassistant.turn_on
      data:
        entity_id: switch.lavalampe
    - delay:
        seconds: 3
    - service: homeassistant.turn_off
      data:
        entity_id: switch.lavalampe
