- alias: "Heizsaison Start"
  initial_state: false
  trigger:
    - platform: state
      entity_id: switch.heizsaison
      from: "off"
      to: "on"
  action:
    - service: climate.set_hvac_mode
      data:
        hvac_mode: "auto"
        entity_id: all
