---
- alias: "Luftentfeuchter on"
  initial_state: true
  trigger:
    - platform: numeric_state
      entity_id: sensor.leq0868600_humidity
      above: 62
  condition:
    - condition: state
      entity_id: switch.pangea
      state: "off"
  action:
    - service: switch.turn_on
      entity_id: switch.leq0531146
- alias: "Luftentfeuchter off"
  initial_state: true
  trigger:
    - platform: numeric_state
      entity_id: sensor.leq0868600_humidity
      below: 57
  action:
    - service: switch.turn_off
      entity_id: switch.leq0531146
