- alias: "Nachtkasterl_off_long_play"
  #  hide_entity: True
  initial_state: "on"
  trigger:
    - platform: mqtt
      topic: hm/status/Schlafzimmer.Taster.unten/PRESS_LONG
    - platform: event
      event_type: homematic.keypress
      event_data:
        #name: Schlafzimmer.Taster
        name: NEQ1543071
        channel: 1
        param: PRESS_LONG
    - platform: event
      event_type: homematic.keypress
      event_data:
        name: Schlafzimmer.Taster
        channel: 1
        param: PRESS_LONG
  action:
    - service: notify.slack
      data_template:
        target: "@cyberkov"
        message: >
          Your aid is needed!
    - service: notify.hannes
      data_template:
        message: >
          Your aid is needed!
    - service: homeassistant.turn_on
      data:
        entity_id: switch.lavalampe
    - delay:
        seconds: 1
    - service: homeassistant.turn_off
      data:
        entity_id: switch.lavalampe
    - delay:
        seconds: 1
    - service: homeassistant.turn_on
      data:
        entity_id: switch.lavalampe
    - delay:
        seconds: 1
    - service: homeassistant.turn_off
      data:
        entity_id: switch.lavalampe
        #- alias: 'Nachtkasterl_off_long_stop'
        #  initial_state: 'on'
        #  trigger:
        #    - platform: mqtt
        #      topic: hm/status/Schlafzimmer.Taster.unten/PRESS_LONG
        #    - platform: event
        #      event_type: homematic.keypress
        #      event_data:
        #        #name: Schlafzimmer.Taster
        #        name: NEQ1543071
        #        channel: 1
        #        param: PRESS_LONG
        #    - platform: event
        #      event_type: homematic.keypress
        #      event_data:
        #        name: Schlafzimmer.Taster
        #        channel: 1
        #        param: PRESS_LONG
        #  condition:
        #    - condition: state
        #      entity_id: media_player.schlafzimmer
        #      state: 'playing'
        #  action:
        #    - service: media_player.media_play_pause
        #      data:
        #        entity_id: media_player.schlafzimmer
