---
entities:
  #  - sensor.hauscyberkovat
  - sensor.speedtest_download
  - sensor.speedtest_ping
  - sensor.speedtest_upload
  - binary_sensor.axon7_status
  - sensor.travis_build_label
  - sensor.travis_status
