entities:
  - binary_sensor.meq0172089_state
  - binary_sensor.meq0186709_state
  - climate.meq0182106
  - climate.meq0182137
  - light.nachtkasterl
  - media_player.lounge
  - sensor.leq0868021_humidity
  - sensor.leq0868021_temperature
  - sensor.mold_schlafzimmer
  - switch.it_2
