---
# Name of the location where Home Assistant is running
name: Home
# Location required to calculate the time the sun rises and sets
latitude: !secret HA_HOME_LATITUDE
longitude: !secret HA_HOME_LONGITUDE
# Impacts weather/sunrise data
elevation: 169
# C for Celsius, F for Fahrenheit
unit_system: metric
# Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
time_zone: Europe/Vienna
customize: !include_dir_merge_named ../customizations
customize_domain: !include ../customizations_domain.yaml
customize_glob: !include ../customizations_glob.yaml
packages: !include_dir_named ../packages
whitelist_external_dirs:
  - /config/tmp
auth_providers:
  - type: homeassistant
  - type: trusted_networks
    trusted_networks:
      - 127.0.0.1
      - ::1
      - 172.17.0.0/24
      - 192.168.1.0/25
