---
device: "/dev/serial/by-id/usb-RFXCOM_RFXtrx433_A1XQFF3C-if00-port0"
#host: 192.168.1.4
#port: 50000
debug: false
automatic_add: true
devices:
  0b11000000f2704201510f60:
    #name: "IT Stecker 1"
    fire_event: true
    device_class: plug
  0b11000300f2704202510f50:
    #name: "IT Stecker 2"
    fire_event: true
    device_class: plug
  0b11000800f2704203510f50:
    #name: "IT Stecker 3"
    device_class: light
    fire_event: true
  0b11000c0001044202510f60:
    #name: "HE Stecker 1"
    device_class: plug
    fire_event: true
  0b11001b0001044203510f60:
    #name: "HE Stecker 2"
    device_class: plug
    fire_event: true
  0b11001f0001044205500060:
    #name: "HE Stecker 4"
    device_class: plug
    fire_event: true
