---
- platform: mjpeg
  mjpeg_url: http://192.168.1.13/mjpg/video.mjpg
  still_image_url: http://192.168.1.13/snapshot.jpg
  username: !secret HA_POOLCAM_USER
  password: !secret HA_POOLCAM_PASSWORD
  name: pool camera
