- alias: 'Automation_Test'
  trigger:
    - platform: state
      entity_id: binary_sensor.hannesbewegungsmelder_motion
      to: 'on'
  condition:
    - condition: state
      entity_id: light.it_stecker_3
      state: 'off'
  action:
    - service: homeassistant.turn_on
      data:
        entity_id: light.it_stecker_3
    - delay:
        seconds: 3
    - service: homeassistant.turn_off
      data:
        entity_id: light.it_stecker_3
